# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-10 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('has_siblings', models.BooleanField()),
                ('exposures', models.CharField(blank=True, max_length=500)),
                ('mutations', models.CharField(blank=True, max_length=500)),
                ('review_status', models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=30)),
            ],
        ),
    ]
