# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-10 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='exposures',
            field=models.CharField(blank=True, max_length=500, verbose_name='Known Environmental Exposures'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_siblings',
            field=models.BooleanField(verbose_name='Siblings?'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mutations',
            field=models.CharField(blank=True, max_length=500, verbose_name='Known Genetic Mutations'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='review_status',
            field=models.CharField(choices=[('Not Reviewed', 'Not Reviewed'), ('Reviewed - Accepted', 'Reviewed - Accepted'), ('Reviewed - Not Accepted', 'Reviewed - Not Accepted')], default='Not Reviewed', max_length=30, verbose_name='Review Status'),
        ),
    ]
