# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-10-10 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20191010_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='exposures',
            field=models.CharField(blank=True, help_text='Comma-delimited list', max_length=500, verbose_name='Known Environmental Exposures'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='mutations',
            field=models.CharField(blank=True, help_text='Comma-delimited list', max_length=500, verbose_name='Known Genetic Mutations'),
        ),
    ]
